### ISSUE TITLE
Problem building rules_jvm_external

### ISSUE THREAD

**Issue by jastice** [JetBrains/bazel-bsp#10] opened 2020-09-07 18:06 UTC
1. clone repo from https://github.com/bazelbuild/rules_jvm_external
2. import
3. try to build all targets

It will fail because some test targets are included:

```
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 3.5.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"]}
Loading: 0 packages loaded
Loading: 
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 3.5.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"]}
Analyzing: 96 targets (0 packages loaded, 0 targets configured)
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
Command aborted with reason ANALYSIS_FAILURE: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /Users/jast/workspace/rules_jvm_external/tests/unit/build_tests/BUILD:66:11: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
INFO: Elapsed time: 0.077s
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
INFO: 0 processes.
ERROR: The Build Event Protocol upload failed: Not retrying publishBuildEvents, no more attempts left: status='Status{code=UNKNOWN, description=null, cause=null}' UNKNOWN: UNKNOWN UNKNOWN: UNKNOWN
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 3.5.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"]}
Analyzing: 96 targets (0 packages loaded, 0 targets configured)
Loading:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
ERROR: Analysis of target '//tests/unit/build_tests:strict_version_neg' failed; build aborted: Analysis failed
```

Related PR: https://github.com/bazelbuild/rules_jvm_external/pull/237

Building the targets separately from command line yields essentially the same error:
```
> bazel query //... | xargs bazel build
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 3.5.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"]}
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_jast/46161c2ded187f0bd0ff099227d4841e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 3.5.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"]}
ERROR: /Users/jast/workspace/rules_jvm_external/tests/unit/build_tests/BUILD:66:11: in genrule rule //tests/unit/build_tests:strict_version_neg_0__deps: target '@strict_visibility_testing//:org_apache_tomcat_tomcat_api' is not visible from target '//tests/unit/build_tests:strict_version_neg_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//tests/unit/build_tests:strict_version_neg' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.089s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 3 targets configured)
    currently loading: @local_config_cc//
    Fetching @kt_java_stub_template; fetching
```

**Comment by jin** [comment] 2020-09-08 01:03
How are you building all targets? `bazel test //...` shouldn't trigger the failing test, because it's marked as `manual`. It's a negative test.

https://github.com/bazelbuild/rules_jvm_external/blob/a3a8053e000f4d6f9a26edced4d0b0f9cecba52c/tests/unit/build_tests/BUILD#L68

`bazel query //... | xargs bazel build` would unintentionally cause the (expected failing) test to be built/run.

**Comment by jastice** [comment] 2020-09-08 10:15
Yes, the issue seems to be that the query used by bazel-bsp gets the manual targets, and IntelliJ passes in all the targets individually for build, rather than requesting a wildcard `build //...` (because it knows nothing about that)

**Comment by jin** [comment] 2020-09-08 10:57
Perhaps try `bazel query '//... except attr("tags", "manual", //...)'`?

**Comment by jastice** [comment] 2020-09-08 11:03
Thanks, that works! Should we expect any problems with other projects if these targets aren't imported into the IDE?

**Comment by andrefmrocha** [comment] 2020-09-08 11:03
> Perhaps try `bazel query '//... except attr("tags", "manual", //...)'`?
The problem is that even though the target is not supposed to be built, it is still a valid target by BSP standards (correct me if I'm wrong). This would mean that we should probably exclude during build, not during import

**Comment by jin** [comment] 2020-09-08 11:06
`manual` targets != un-buildable targets, so yes, it's supposed to be built, but only if the user requests that target explicitly. 

Could you surface this as an user input instead, in the same style as the IntelliJ plugin's project view `targets` section?

**Comment by andrefmrocha** [comment] 2020-09-08 11:09
Yes I do agree that would be a better solution long-term, and I'm hoping that to be the case, but for now it would be best if IntelliJ didn't try to build it (since it is the `canBuild` flag that determines this) and if the user wanted to do so, they could do it through the command line.

**Comment by jastice** [comment] 2020-09-08 11:14
I think we can expose this easily through the [`BuildTarget.tags`](https://build-server-protocol.github.io/docs/specification.html#build-target) in the protocol in a backwards-compatible way and give it special handling in the IDE. Meanwhile I'll just build the project manually from command line

**Comment by abrams27** [comment] 2022-03-16 14:15
I'm trying to reproduce the issue and now I'm getting another error:
```
ERROR: While resolving toolchains for target //tests/integration/override_targets:sceneform_rendering: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//tests/integration/override_targets:sceneform_rendering' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
```

the import itself seems working, what else should I test?

**Comment by abrams27** [comment] 2022-04-14 09:56
i cant reproduce it - the codebase itself breaks

moved to: https://youtrack.jetbrains.com/issue/BAZEL-40

**Closed by abrams27** 2022-04-14 09:56 UTC
